name: Feature branch push

on:
  push:
    branches:
      - 'feature/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: echo "Feature Code push"
          # Build steps go here
